package com.sangsang.autoblog.domain.model;

import java.time.LocalDateTime;

public class PostContent {
    
    public final String rawMarkdown;
    public final String title;
    public final String body;
    public final String[] tags;
    public final String imageUrl;
    public final String summary;
    public final LocalDateTime date;

    private PostContent(
        String rawMarkdown,
        String title,
        String body,
        String[] tags,
        String imageUrl,
        String summary
    ){
        this.rawMarkdown = rawMarkdown;
        this.title = title;
        this.body = body;
        this.tags = tags;
        this.imageUrl = imageUrl;
        this.summary = summary;
        this.date = LocalDateTime.now();
    }

    public static PostContent markdownContentFrom(String rawMarkdown){
        return new PostContent(rawMarkdown, null, null, null, null, null);
    }

    public static PostContent postContentFrom(String title, String body, String[] tags, String imageUrl, String summary) {
        return new PostContent(null, title, body, tags, imageUrl, summary);
    }

    public static PostContent getPreviewPost(){
        String title = "[Generated Title] How to build a blog with AI";
        String body = "[Generated Body] This is a sample blog post generated by AI...";
        String[] tags = new String[]{"AI", "Blogging", "Technology"};
        String imageUrl = "https://example.com/sample-image.jpg";
        String summary = "[Generated Summary] A brief overview of building a blog using AI technologies.";
        return postContentFrom(title, body, tags, imageUrl, summary);
    }

    public static PostContent getPreviewMarkdown(){
        String sampleRawMarkdown = 
"""
# 마크다운이란?

## Summary
마크다운은 일반 텍스트로 문서를 작성할 때 서식을 쉽게 지정할 수 있도록 도와주는 경량 마크업 언어입니다. 배우기 쉽고 가독성이 뛰어나며, 다양한 플랫폼에서 널리 사용되어 개발자뿐만 아니라 일반 사용자에게도 유용합니다. 복잡한 워드 프로세서 없이 깔끔한 문서를 빠르게 만들 수 있습니다.

## Body

### 마크다운이란 무엇인가요?
마크다운(Markdown)은 2004년 존 그루버(John Gruber)가 개발한 텍스트 기반의 마크업 언어입니다. HTML과 같이 복잡한 태그 없이도 특수문자를 사용하여 텍스트에 서식을 적용할 수 있도록 고안되었습니다. `.md` 또는 `.markdown` 확장자를 가지며, 사람도 쉽게 읽을 수 있는 형태로 작성됩니다.

### 왜 마크다운을 사용할까요?
마크다운이 널리 사용되는 주요 이유는 다음과 같습니다:

*   **쉬운 학습과 사용**: 문법이 매우 간단하여 몇 분 안에 기본적인 사용법을 익힐 수 있습니다.
*   **뛰어난 가독성**: 소스 코드 자체가 읽기 쉽고 깔끔하여, 별도의 렌더링 없이도 내용을 이해하기 용이합니다.
*   **다양한 플랫폼 지원**: GitHub, GitLab, Notion, Obsidian, VS Code 등 수많은 도구와 서비스에서 마크다운을 지원합니다.
*   **버전 관리 용이**: 텍스트 파일이므로 Git과 같은 버전 관리 시스템에서 변경 이력을 추적하고 병합하기 편리합니다.
*   **빠른 문서 작성**: 마우스를 사용하지 않고 키보드만으로 빠르게 문서를 구조화하고 서식을 적용할 수 있습니다.

### 마크다운 기본 문법

가장 자주 사용되는 마크다운 문법을 통해 실제 적용 방법을 알아보겠습니다.

#### 1. 제목 (Headings)
`#`의 개수로 제목의 단계를 표현합니다. `#`은 H1, `##`은 H2와 같습니다.

```markdown
# 이것은 H1 제목입니다
## 이것은 H2 제목입니다
### 이것은 H3 제목입니다
```

#### 2. 목록 (Lists)
순서 없는 목록은 `*`, `-`, `+` 중 하나를 사용하고, 순서 있는 목록은 숫자를 사용합니다.

```markdown
* 첫 번째 항목
* 두 번째 항목
  - 하위 항목 1
  - 하위 항목 2

1. 순서 있는 목록 1
2. 순서 있는 목록 2
```

#### 3. 강조 (Emphasis)
텍스트를 기울이거나(이탤릭) 굵게(볼드) 표시할 수 있습니다.

```markdown
*기울임체 텍스트* 또는 _기울임체 텍스트_
**굵은 텍스트** 또는 __굵은 텍스트__
***굵고 기울인 텍스트***
```

#### 4. 코드 블록 (Code Blocks)
인라인 코드는 백틱(`)으로 감싸고, 여러 줄의 코드 블록은 세 개의 백틱(```)으로 감싸며 언어를 지정할 수 있습니다.

```markdown
`int a = 10;` 처럼 인라인 코드를 작성할 수 있습니다.

```python
def hello_world():
    print("Hello, Markdown!")
```
```

#### 5. 링크 (Links)
`[링크 텍스트](URL)` 형식으로 작성합니다.

```markdown
[Google로 이동](https://www.google.com)
```

#### 6. 이미지 (Images)
`![대체 텍스트](이미지 URL)` 형식으로 작성합니다. 링크와 유사하지만 앞에 `!`가 붙습니다.

```markdown
![마크다운 로고](https://upload.wikimedia.org/wikipedia/commons/4/48/Markdown-mark.svg)
```

#### 7. 인용문 (Blockquotes)
`>` 기호를 사용하여 인용문을 표시합니다.

```markdown
> "마크다운은 정말 편리합니다!"
> - TIL 블로그 중에서
```

#### 8. 수평선 (Horizontal Rules)
`---`, `***`, `___` 중 세 개 이상을 사용해 수평선을 그을 수 있습니다.

```markdown
---
```

이처럼 마크다운은 간단한 문법만으로도 체계적이고 가독성 높은 문서를 작성할 수 있게 해주는 강력한 도구입니다.

## Tags
- 마크다운
- 개발
- 문서작성
- TIL
- 텍스트
""";
        
        return markdownContentFrom(sampleRawMarkdown);
    }

}


// """
// <h1>TIL: 마크다운이란?</h1>
// <h2>Summary</h2>
// <p>마크다운(Markdown)은 텍스트 기반의 가벼운 마크업 언어로, HTML처럼 복잡한 태그 없이도 빠르고 쉽게 문서를 작성하고 서식을 지정할 수 있게 해줍니다. 개발 블로그, README 파일, 문서화 등 다양한 곳에서 활용되며, 가독성과 편리함이 큰 장점입니다.</p>
// <h2>Body</h2>
// <h3>마크다운이란?</h3>
// <p>마크다운(Markdown)은 텍스트 기반의 경량 마크업 언어로, 일반 텍스트 문서를 작성할 때 서식을 입힐 수 있는 간단한 문법을 제공합니다. 2004년 존 그루버(John Gruber)가 개발했으며, 읽기 쉽고 쓰기 쉬운 평문(plain text) 형태로 작성되면서도 웹 페이지로 쉽게 변환될 수 있도록 고안되었습니다.</p>
// <h3>왜 마크다운을 사용할까요?</h3>
// <ul>
// <li><strong>간결하고 직관적인 문법:</strong> 복잡한 HTML 태그를 외울 필요 없이, 특수 기호 몇 가지만으로 빠르게 서식을 적용할 수 있습니다.</li>
// <li><strong>뛰어난 가독성:</strong> 마크다운 원본 자체도 읽기 쉬운 형태로 작성됩니다.</li>
// <li><strong>높은 범용성:</strong> 개발 블로그, README 파일, 문서화, 이메일, 채팅 등 수많은 플랫폼과 도구에서 지원됩니다.</li>
// <li><strong>쉬운 변환:</strong> HTML, PDF 등 다양한 형식으로 손쉽게 변환할 수 있습니다.</li>
// <li><strong>버전 관리 용이:</strong> 일반 텍스트 파일이므로 Git과 같은 버전 관리 시스템에서 변경 이력을 추적하기 매우 편리합니다.</li>
// </ul>
// <h3>마크다운 기본 문법</h3>
// <p>자주 사용되는 핵심 문법을 예시와 함께 살펴봅시다.</p>
// <h4>1. 제목 (Headings)</h4>
// <p><code>#</code> 기호를 사용하여 제목을 표현하며, <code>#</code>의 개수로 제목의 단계를 나타냅니다. (H1부터 H6까지)</p>
// <pre><code class="language-markdown"># 이것은 H1 제목입니다
// ## 이것은 H2 제목입니다
// ### 이것은 H3 제목입니다
// </code></pre>
// <h4>2. 문단 및 줄바꿈 (Paragraphs &amp; Line Breaks)</h4>
// <p>문단은 비어있는 줄(blank line)로 구분합니다. 줄바꿈은 스페이스 2개를 입력하거나 <code>&lt;br/&gt;</code> 태그를 사용합니다.</p>
// <pre><code class="language-markdown">첫 번째 문단입니다.

// 두 번째 문단입니다.

// 이것은 한 줄에  
// 표시됩니다. (스페이스 두 개)
// </code></pre>
// <h4>3. 굵게, 기울임 (Bold &amp; Italic)</h4>
// <p>별표(<code>*</code>) 또는 밑줄(<code>_</code>)을 사용합니다. 두 개를 사용하면 굵게, 한 개를 사용하면 기울임입니다.</p>
// <pre><code class="language-markdown">**굵은 글씨** 또는 __굵은 글씨__
// *기울임 글씨* 또는 _기울임 글씨_
// </code></pre>
// <h4>4. 목록 (Lists)</h4>
// <p>순서 없는 목록은 <code>*</code>, <code>-</code>, <code>+</code> 중 하나를 사용하고, 순서 있는 목록은 숫자와 <code>.</code>을 사용합니다.</p>
// <pre><code class="language-markdown">* 순서 없는 목록 1
//   * 하위 목록 1.1
// 1. 순서 있는 목록 1
// 2. 순서 있는 목록 2
//    1. 하위 목록 2.1
// </code></pre>
// <h4>5. 링크 (Links)</h4>
// <p><code>[링크 텍스트](URL)</code> 형식으로 작성합니다.</p>
// <pre><code class="language-markdown">[Google로 이동](https://www.google.com)
// </code></pre>
// <h4>6. 이미지 (Images)</h4>
// <p><code>![대체 텍스트](이미지 URL)</code> 형식으로 작성합니다. 링크와 유사하지만 앞에 <code>!</code>가 붙습니다.</p>
// <pre><code class="language-markdown">![Markdown 로고](https://upload.wikimedia.org/wikipedia/commons/4/48/Markdown-mark.svg)
// </code></pre>
// <h4>7. 코드 블록 (Code Blocks)</h4>
// <p>인라인 코드는 백틱(<code>`</code>)으로 감싸고, 여러 줄의 코드 블록은 백틱 세 개(<code>```</code>)로 감쌉니다. 언어를 명시하면 문법 강조(Syntax Highlighting)가 적용됩니다.</p>
// <pre><code class="language-markdown">인라인 코드는 `print(&quot;Hello World&quot;)` 와 같이 표현합니다.

// ```python
// def hello_world():
//     print(&quot;Hello, Markdown!&quot;)
// </code></pre>
// <pre><code>
// #### 8. 인용문 (Blockquotes)
// `&gt;` 기호를 사용합니다.

// ```markdown
// &gt; 이 글은 마크다운에 대한 설명입니다.
// &gt; &gt; 중첩된 인용문도 가능합니다.
// </code></pre>
// <h4>9. 수평선 (Horizontal Rule)</h4>
// <p>세 개 이상의 <code>*</code>, <code>-</code>, <code>_</code>를 사용하여 수평선을 그립니다.</p>
// <pre><code class="language-markdown">---
// ***
// ___
// </code></pre>
// <h2>Tags</h2>
// <ul>
// <li>마크다운</li>
// <li>개발</li>
// <li>블로그</li>
// <li>문서화</li>
// <li>생산성</li>
// </ul>
// """;